export default function HomePage() {
  return (
    <div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
      <div>home/browse page</div>
    </div>
  );
}